name: QA Workflow

on: push

jobs:
  merge-into-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Print Changed files
        run : |
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [[ $changed_file == *"stack"* ]]; then
              parsed=$(echo "$changed_file" | awk -F[//] '{print $2}' )
              echo "$parsed"
            fi
          done

