name: QA Workflow

on: push

jobs:
  merge-into-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Print Changed files
        run : |
          echo "${{ steps.changed-files.outputs.all }}"

