name: QA Workflow

on: push

jobs:
  get-changed-stacks:
    runs-on: ubuntu-latest
    outputs:
      changed_stack_array: ${{ steps.modified_files_list.outputs.stringList }}
    steps:
      - uses: actions/checkout@v2.1.0
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Print Changed files
        id: updated_stacks
        run : |
          arr=()
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [[ $changed_file == *"stack"* ]]; then
              parsed=$(echo "$changed_file" | awk -F[//] '{print $2}' )
              arr+=("$parsed")
            fi
          done
          output_array=$(printf '%s\n' "${arr[@]}" | jq -R . | jq -s .)
          echo ::set-output name=arr::$output_array
      - name: Create list of modified files
        id: modified_files_list
        uses: lucaspinheirogit/list-from-string-array-action@v1.4.3
        with:
          stringArray: ${{ steps.updated_stacks.outputs.arr }}

  plan-stack:
    runs-on: ubuntu-latest
    needs: get-changed-stacks
    strategy:
      matrix:
        stack_name: ${{ needs.get-changed-stacks.outputs.changed_stack_array }}
      max-parallel: 0
    steps:
      - name: Log stack
        run: echo "${{ matrix.stack_name }}"





